### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by pablogarcor** [ozluy/react-stripe-script-loader#1]
The app cant compile because of the StripeScriptLoader component. It seems like is the loader prop fault
![error](https://user-images.githubusercontent.com/49307255/65086224-46191b00-d9b1-11e9-9ee0-1fb4a1e97800.PNG)

**Comment by ozluy** [comment]
@pablogarcor  can you please share react and react-dom  versions?

**Comment by ozluy** [comment]
Probably your react version does not support fragments which came to react world after version <a href="https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html">16.2.0</a>  so I created older version support under following script please try and reopen issue if it occurs again. It has `react-version-15` tag, please dont skip that.

`npm install react-stripe-script-loader@react-version-15 -S`

**Comment by pablogarcor** [comment]
Thank you very much, ill try asap :+1:
