### ISSUE TITLE
What is the `uniqueId` which this component takes in ?

### ISSUE THREAD

**Issue by chandrajob365** [ozluy/react-stripe-script-loader#2]
What is the `uniqueId` which this component takes in ? Does this unique id needs to be created in index.html ?

**Comment by ozluy** [comment]
Hello @chandrajob365 ,
`uniqueId`  is id of `script` tag, its used to check if the tag already exists, to prevent creating same script tag again every time. Implemented like following snippet....

```js
const script = document.createElement('script')
script.src = src
script.id = uniqueId
```
