### ISSUE TITLE
payment button

### ISSUE THREAD

**Issue by mariomeraz** [ozluy/react-stripe-script-loader#4]
Hello,

it is possible to use the payment button ?

**Comment by ozluy** [comment]
https://codesandbox.io/s/react-stripe-script-loader-scktw
hey @mariomeraz  can you check this example?

**Comment by mariomeraz** [comment]
@ozluy like a boss, thks so much, iam noob in react

**Comment by ozluy** [comment]
@mariomeraz closing the issue 
thank you for reporting, I have updated link little bit you might need to check again (removed unused code)
