### ISSUE TITLE
useState is not a function

### ISSUE THREAD

**Issue by ekkis** [ozluy/react-stripe-script-loader#6]
I'm trying to use Mathieu Loutre's NextJs implementation of Stripe (see: https://github.com/MathieuLoutre/nextjs-stripe-elements) but it breaks as documented here: https://github.com/MathieuLoutre/nextjs-stripe-elements/issues/2

however, I found this module that should fix the problem.  I've implemented it by modifying his code like this:
```js
import { StripeProvider, Elements } from 'react-stripe-elements'
import StripeScriptLoader from 'react-stripe-script-loader'
import CheckoutElement from './CheckoutElement'

export default (props) =>
	<StripeScriptLoader
		// uniqueId={props.myUniqueId || 'myUniqueId'}
		uniqueId='myUniqueId'
		script='https://js.stripe.com/v3/'
		loader="Loading..."
	>
	<StripeProvider apiKey="pk_test">
		<Elements>
			<CheckoutElement />
		</Elements>
	</StripeProvider>
	</StripeScriptLoader>
```
however, when I run this code I get the errors trace below:

> (0,_react.useState) is not a function. (In '(0,_react.useState)({})', '(0,_react.useState)' is undefined)
> StripeScriptLoader@http://localhost:3000/_next/1588708107908/page/:8551:1849
> renderWithHooks@http://localhost:3000/_next/1588708107908/commons.js:14809:27
> mountIndeterminateComponent@http://localhost:3000/_next/1588708107908/commons.js:17488:28
> callCallback@http://localhost:3000/_next/1588708107908/commons.js:194:19
> dispatchEvent@[native code]
> invokeGuardedCallbackDev@http://localhost:3000/_next/1588708107908/commons.js:243:29
> invokeGuardedCallback@http://localhost:3000/_next/1588708107908/commons.js:298:36
> beginWork$1@http://localhost:3000/_next/1588708107908/commons.js:23209:28
> performUnitOfWork@http://localhost:3000/_next/1588708107908/commons.js:22163:23
> workLoopSync@http://localhost:3000/_next/1588708107908/commons.js:22136:39
> performSyncWorkOnRoot@http://localhost:3000/_next/1588708107908/commons.js:21762:21
> scheduleUpdateOnFiber@http://localhost:3000/_next/1588708107908/commons.js:21194:28
> updateContainer@http://localhost:3000/_next/1588708107908/commons.js:24379:15
> http://localhost:3000/_next/1588708107908/commons.js:24764:22
> unbatchedUpdates@http://localhost:3000/_next/1588708107908/commons.js:21909:14
> legacyRenderSubtreeIntoContainer@http://localhost:3000/_next/1588708107908/commons.js:24763:21
> renderReactElement@http://localhost:3000/_next/1588708107908/main.js:18337:30
> _callee4$@http://localhost:3000/_next/1588708107908/main.js:18100:31
> tryCatch@http://localhost:3000/_next/1588708107908/main.js:6763:44
> invoke@http://localhost:3000/_next/1588708107908/main.js:6997:30
> step@http://localhost:3000/_next/1588708107908/main.js:1905:30
> initializePromise@[native code]
> Promise@[native code]
> F@http://localhost:3000/_next/1588708107908/main.js:48:33
> http://localhost:3000/_next/1588708107908/main.js:1902:33
> tryCatch@http://localhost:3000/_next/1588708107908/main.js:6763:44
> invoke@http://localhost:3000/_next/1588708107908/main.js:6997:30
> step@http://localhost:3000/_next/1588708107908/main.js:1905:30
> initializePromise@[native code]
> Promise@[native code]
> F@http://localhost:3000/_next/1588708107908/main.js:48:33
> http://localhost:3000/_next/1588708107908/main.js:1902:33
> http://localhost:3000/_next/1588708107908/main.js:18313:19
> forEach@[native code]
> http://localhost:3000/_next/1588708107908/main.js:5946:34
> notify@http://localhost:3000/_next/1588708107908/main.js:11896:33
> _callee2$@http://localhost:3000/_next/1588708107908/main.js:11348:28
> tryCatch@http://localhost:3000/_next/1588708107908/main.js:6763:44
> invoke@http://localhost:3000/_next/1588708107908/main.js:6997:30
> step@http://localhost:3000/_next/1588708107908/main.js:1905:30
> http://localhost:3000/_next/1588708107908/main.js:1916:17
> promiseReactionJob@[native code]

what is missing? isn't anything ever easy?

**Comment by ekkis** [comment]
ok.  the answer is Mattheu's project is ancient.  I did `npm update next@latest react-stripe-elements@latest` and it all seems to work

**Comment by ozluy** [comment]
@ekkis in case you get that error for an older version of react i have an important note :) here
https://github.com/ozluy/react-stripe-script-loader/blob/master/readme.md#important-note
